# Diplomatura en IA - UP 
### Practico N°2 - Jun26
### Alumno: Gonzalez Marta Elizabeth 
### Notebook 01  - Lectura y descubrimientos -

### Lirerias

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
print("Librerías cargadas")

Librerías cargadas

In [2]:
# Visualizar en que repositorio estas posicionado:

import os
os.getcwd()

'C:\\Users\\Usuario\\DiploIA\\Practica\\Practico2\\notebooks'

In [3]:
# Lista de archivos en del repositorio:

import os
os.listdir()

['.ipynb_checkpoints',
 '01_lectura_y_discovery.ipynb',
 '02_eda.ipynb',
 '03_preprocesamiento.ipynb',
 '04_entrenamiento_y_optimizacion.ipynb',
 '05_validacion.ipynb',
 '06_prediccion.ipynb',
 'best_model.pkl',
 'Untitled2.ipynb']

#### Variables y Carga del Dataset

In [4]:
# Ubicacion del dataset excel:

PATH = "../data/raw/smoking_prediction.xlsx"

In [5]:
# Lectura del archivo:

df = pd.read_excel(PATH)

#### Lectura de Datos

In [6]:
# Dimensiones

print(f"Cantidad de filas: {df.shape[0]}")
print(f"Cantidad de columnas: {df.shape[1]}")

Cantidad de filas: 50000
Cantidad de columnas: 27

In [6]:
# Primeras observaciones:

df.head()

,ID,gender,age,height(cm),weight(kg),waist(cm),eyesight(left),eyesight(right),hearing(left),hearing(right),...,hemoglobin,Urine protein,serum creatinine,AST,ALT,Gtp,oral,dental caries,tartar,smoking
0,0,F,40,155,60,3.377083,0.043056,0.041667,0.041667,0.041667,...,0.506250,0.041667,0.004861,0.750000,0.791667,1.125000,Y,0,Y,0
1,1,F,40,160,60,3.375000,0.005556,0.004167,0.041667,0.041667,...,0.504861,0.041667,0.004167,0.916667,0.791667,0.750000,Y,0,Y,0
2,2,M,55,170,60,3.333333,0.005556,0.005556,0.041667,0.041667,...,0.630556,0.041667,0.041667,0.875000,0.666667,0.916667,Y,0,N,1
3,3,M,40,165,70,3.666667,0.045139,0.045139,0.041667,0.041667,...,0.588194,0.041667,0.041667,0.791667,1.083333,0.750000,Y,0,Y,0
4,4,F,40,155,60,3.583333,0.041667,0.041667,0.041667,0.041667,...,0.503472,0.041667,0.004167,0.666667,0.583333,0.916667,Y,0,N,0

In [7]:
# Ultimas observaciones:
df.tail()

,ID,gender,age,height(cm),weight(kg),waist(cm),eyesight(left),eyesight(right),hearing(left),hearing(right),...,hemoglobin,Urine protein,serum creatinine,AST,ALT,Gtp,oral,dental caries,tartar,smoking
49995,27343,M,50,160,55,2.961806,0.004861,0.005556,0.041667,0.041667,...,0.547917,0.041667,0.041667,0.958333,0.583333,0.916667,Y,0,Y,1
49996,27350,M,30,170,70,3.333333,0.045139,0.041667,0.041667,0.041667,...,0.629167,0.041667,0.006250,1.083333,1.208333,0.750000,Y,1,Y,1
49997,27351,M,20,165,65,3.541667,0.045139,0.045139,0.041667,0.041667,...,0.670833,0.041667,0.005556,1.458333,1.458333,2.916667,Y,0,Y,1
49998,27352,F,60,160,45,2.961806,0.002778,0.002778,0.041667,0.041667,...,0.584028,0.041667,0.004861,0.791667,0.666667,1.041667,Y,1,Y,0
49999,27354,M,45,170,80,4.000000,0.045139,0.041667,0.041667,0.041667,...,0.625000,0.041667,0.041667,1.166667,1.708333,2.583333,Y,1,N,1

In [8]:
# Muestra aleatoria:

df.sample(n=10, random_state=42)

,ID,gender,age,height(cm),weight(kg),waist(cm),eyesight(left),eyesight(right),hearing(left),hearing(right),...,hemoglobin,Urine protein,serum creatinine,AST,ALT,Gtp,oral,dental caries,tartar,smoking
33553,41917,M,55,175,75,3.750000,0.041667,0.041667,0.041667,0.041667,...,0.586111,0.041667,0.004167,1.208333,1.000000,2.416667,Y,1,N,0
9427,11817,F,40,160,55,2.797222,0.006250,0.004861,0.041667,0.041667,...,0.544444,0.041667,0.004167,1.250000,0.791667,0.375000,Y,0,Y,0
199,260,F,40,150,65,3.836806,0.005556,0.004861,0.041667,0.041667,...,0.545833,0.041667,0.004167,0.875000,1.250000,0.916667,Y,0,N,0
12447,15517,F,50,155,65,3.708333,0.043056,0.043056,0.041667,0.041667,...,0.587500,0.041667,0.004167,1.208333,0.958333,0.666667,Y,0,N,0
39489,49334,F,45,150,50,2.750000,0.041667,0.001389,0.041667,0.041667,...,0.463194,0.041667,0.006250,1.000000,0.583333,0.625000,Y,0,Y,0
42724,53412,F,55,150,65,3.208333,0.005556,0.003472,0.041667,0.041667,...,0.545833,0.041667,0.003472,0.708333,0.750000,0.708333,Y,0,Y,0
10822,13539,M,40,170,65,3.083333,0.041667,0.043056,0.041667,0.041667,...,0.588194,0.041667,0.041667,0.791667,1.250000,2.083333,Y,0,N,1
49498,24826,F,65,150,50,3.166667,0.005556,0.002778,0.041667,0.041667,...,0.586806,0.041667,0.004861,1.000000,0.708333,0.583333,Y,1,Y,0
4144,5206,M,40,180,85,4.041667,0.045139,0.043056,0.041667,0.041667,...,0.587500,0.041667,0.041667,0.958333,1.541667,3.625000,Y,0,Y,1
36958,46188,M,45,175,80,3.711806,0.006250,0.006250,0.041667,0.041667,...,0.667361,0.041667,0.043056,1.875000,2.250000,3.416667,Y,0,N,0

In [9]:
# Estructura:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 27 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   50000 non-null  int64
 1   gender               50000 non-null  object
 2   age                  50000 non-null  int64
 3   height(cm)           50000 non-null  int64
 4   weight(kg)           50000 non-null  int64
 5   waist(cm)            50000 non-null  float64
 6   eyesight(left)       50000 non-null  float64
 7   eyesight(right)      50000 non-null  float64
 8   hearing(left)        50000 non-null  float64
 9   hearing(right)       50000 non-null  float64
 10  systolic             50000 non-null  float64
 11  relaxation           50000 non-null  float64
 12  fasting blood sugar  50000 non-null  float64
 13  Cholesterol          50000 non-null  float64
 14  triglyceride         50000 non-null  float64
 15  HDL                  50000 non-null  float64
 16  LDL                  50000 non-null  float64
 17  hemoglobin           50000 non-null  float64
 18  Urine protein        50000 non-null  float64
 19  serum creatinine     50000 non-null  float64
 20  AST                  50000 non-null  float64
 21  ALT                  50000 non-null  float64
 22  Gtp                  50000 non-null  float64
 23  oral                 50000 non-null  object
 24  dental caries        50000 non-null  int64
 25  tartar               50000 non-null  object
 26  smoking              50000 non-null  int64
dtypes: float64(18), int64(6), object(3)
memory usage: 10.3+ MB

In [10]:
# Diccionario de Variables

df.columns

Index(['ID', 'gender', 'age', 'height(cm)', 'weight(kg)', 'waist(cm)',
       'eyesight(left)', 'eyesight(right)', 'hearing(left)', 'hearing(right)',
       'systolic', 'relaxation', 'fasting blood sugar', 'Cholesterol',
       'triglyceride', 'HDL', 'LDL', 'hemoglobin', 'Urine protein',
       'serum creatinine', 'AST', 'ALT', 'Gtp', 'oral', 'dental caries',
       'tartar', 'smoking'],
      dtype='object')

In [11]:
# Estadistica Descritptiva:

df.describe().T

,count,mean,std,min,25%,50%,75%,max
ID,50000.0,26284.994580,16015.070567,0.000000,12499.750000,24999.500000,40034.250000,55690.000000
age,50000.0,44.189300,12.090086,20.000000,40.000000,40.000000,55.000000,85.000000
height(cm),50000.0,164.652000,9.208778,130.000000,160.000000,165.000000,170.000000,190.000000
weight(kg),50000.0,65.878700,12.831355,30.000000,55.000000,65.000000,75.000000,135.000000
waist(cm),50000.0,3.414852,0.386765,2.125000,3.166667,3.416667,3.666667,5.375000
eyesight(left),50000.0,0.028446,0.024007,0.000694,0.005556,0.041667,0.043056,0.381250
eyesight(right),50000.0,0.028304,0.024216,0.000694,0.005556,0.041667,0.043056,0.381250
hearing(left),50000.0,0.042736,0.006588,0.041667,0.041667,0.041667,0.041667,0.083333
hearing(right),50000.0,0.042758,0.006655,0.041667,0.041667,0.041667,0.041667,0.083333
systolic,50000.0,5.062531,0.570100,2.958333,4.666667,5.000000,5.416667,10.000000
relaxation,50000.0,3.167326,0.403490,1.666667,2.916667,3.166667,3.416667,6.083333
fasting blood sugar,50000.0,4.137704,0.865933,1.916667,3.708333,4.000000,4.333333,21.041667
Cholesterol,50000.0,8.205148,1.514168,2.291667,7.166667,8.125000,9.166667,18.541667
triglyceride,50000.0,5.275111,2.980790,0.333333,3.083333,4.500000,6.666667,41.625000
HDL,50000.0,2.387543,0.615559,0.166667,1.958333,2.291667,2.750000,25.750000
LDL,50000.0,4.790698,1.709238,0.041667,3.833333,4.708333,5.666667,77.500000
hemoglobin,50000.0,0.593785,0.065870,0.172917,0.545833,0.588889,0.630556,0.875694
Urine protein,50000.0,0.045290,0.016872,0.041667,0.041667,0.041667,0.041667,0.250000
serum creatinine,50000.0,0.018821,0.018432,0.000694,0.005556,0.006250,0.041667,0.462500
AST,50000.0,1.093193,0.827986,0.250000,0.791667,0.958333,1.208333,54.625000
ALT,50000.0,1.129345,1.327431,0.041667,0.625000,0.875000,1.291667,121.416667
Gtp,50000.0,1.668142,2.110347,0.041667,0.708333,1.041667,1.833333,41.625000
dental caries,50000.0,0.213120,0.409516,0.000000,0.000000,0.000000,0.000000,1.000000
smoking,50000.0,0.366580,0.481875,0.000000,0.000000,0.000000,1.000000,1.000000

In [12]:
# Analisis de Valores Nulos

nulos = pd.DataFrame({
    'Cantidad': df.isnull().sum(),
    'Porcentaje': (df.isnull().sum()/len(df))*100
})

nulos.sort_values('Porcentaje', ascending=False)

                     Cantidad  Porcentaje
ID                          0         0.0
triglyceride                0         0.0
tartar                      0         0.0
dental caries               0         0.0
oral                        0         0.0
Gtp                         0         0.0
ALT                         0         0.0
AST                         0         0.0
serum creatinine            0         0.0
Urine protein               0         0.0
hemoglobin                  0         0.0
LDL                         0         0.0
HDL                         0         0.0
Cholesterol                 0         0.0
gender                      0         0.0
fasting blood sugar         0         0.0
relaxation                  0         0.0
systolic                    0         0.0
hearing(right)              0         0.0
hearing(left)               0         0.0
eyesight(right)             0         0.0
eyesight(left)              0         0.0
waist(cm)                   0         0.0
weight(kg)                  0         0.0
height(cm)                  0         0.0
age                         0         0.0
smoking                     0         0.0

In [13]:
# Valores faltantes:

df.isnull().sum().sum()

np.int64(0)

In [14]:
# Registros Duplicados:

duplicados = df.duplicated().sum()

print("Duplicados:", duplicados)

Duplicados: 0

In [15]:
# Variables Categoricas:

categoricas = df.select_dtypes(include=['object'])

categoricas.columns

Index(['gender', 'oral', 'tartar'], dtype='object')

In [16]:
# Variable Objetivo - Distribucion:

df['smoking'].value_counts()

smoking
0    31671
1    18329
Name: count, dtype: int64

In [17]:
# Variable Objetivo - Porcentaje:

round(
    df['smoking'].value_counts(normalize=True)*100,
    2
)

smoking
0    63.34
1    36.66
Name: proportion, dtype: float64

In [18]:
# Exportación para la Notebook 02

df.to_csv(
    "../data/processed/01_dataset_analizado.csv",
    index=False
)

print("Archivo exportado correctamente")

Archivo exportado correctamente